### PR TITLE
Fix for deleted branch on github fork breaking all component installs

### PR DESCRIPTION
**Pull request by cristiandouce**

### CODE REVIEW

**Comment by timaschew** [comment]
which branch was deleted?

**Comment by cristiandouce** [comment]
no, you are right. Sorry. I'm tracking down a recent EISDIR error from npm install. Got here and didn't saw the branch, but it's a tag. There is an issue with one dependency missing a package.json or something like that.

**Comment by cristiandouce** [comment]
```
MBP:test cristiandouce$ npm i component-remotes
npm ERR! addLocal Could not install /var/folders/tb/90xr04011rj3tb611whxl5w40000gn/T/npm-30569-55b582d0/git-cache-fe9e1263e9f4/734ff0028274ab4254d2c06e67efbf2dceaf2b72
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "component-remotes"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cristiandouce/Work/apps/test/npm-debug.log
```

**Comment by cristiandouce** [comment]
@timaschew there is actually an issue with the tag:

```
MBP:test cristiandouce$ npm i 'timaschew/cogent#fix-redirects'
npm WARN peerDependencies The peer dependency co@3 included from cogent will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! addLocal Could not install /var/folders/tb/90xr04011rj3tb611whxl5w40000gn/T/npm-30682-91486b18/git-cache-f338219c498d/734ff0028274ab4254d2c06e67efbf2dceaf2b72
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "timaschew/cogent#fix-redirects"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cristiandouce/Work/apps/test/npm-debug.log
```

using:

```
{ npm: '2.10.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.4',
  openssl: '1.0.1m',
  uv: '1.5.0',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

**Comment by cristiandouce** [comment]
But when you `npm i cogent` it works.

**Comment by timaschew** [comment]
I'm confused, because this tag did never exist, that was just the version in the package.json

but I can't install any branch of the repo `timaschew/cogent`

The latest cogent version doesn't work, because there are some breaking changes

**Comment by cristiandouce** [comment]
@timaschew the tag exists as this

image

it's a tag, not a branch.

and whenever I install that with npm, i get that error.

I've managed to run npm i on each dependency to track the issue. Now when I do

`npm i proxy-agent` i get that error log. So I'm guessing it's an issue with one dependency of `proxy-agent@^1`

If you run an npm cache clean first, you should be able to notice the log error. I've managed to reproduce it with at least 3 other colleagues.

**Comment by timaschew** [comment]
oh yes, right, but npm should handle both: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

I don't know what happened, looks like npm is broken

`npm i timaschew/cogent` is also not working, but `npm i cojs/cogent` is working fine

**Comment by timaschew** [comment]
oh `npm i timaschew/cogent#1.0.0` is working

**Comment by cristiandouce** [comment]
Following: TooTallNate/node-proxy-agent#7

I've noticed that `cojs/cogent` no longer uses `proxy-agent` as a dependency. That is why `npm i timaschew/cogent#1.0.0` works but the fix tag doesn't (because it still depends on `proxy-agent` which is broken on npm install)

**Comment by cristiandouce** [comment]
@timaschew is there any smooth way you could think of re-basing the fix tag `fix-redirect` from `1.0.0` and publishing a `component-remotes` fix to npm?

There is some deep bad-a.. dependency that broke everything from `proxy-agent` down. I'm not still sure which is it :dancers: hahaha There were no updates on `proxy-agent` so I figure it must be one dependency of it.

**Comment by timaschew** [comment]
okay it works if I pin proxy-agent to 1.0.0, npm is really a mess

**Comment by timaschew** [comment]
I replaced the tag, see https://github.com/timaschew/cogent/releases
You should be able to install component and component-remotes.

To avoid these issues, you can use a shrinkwrap file ;)

**Comment by cristiandouce** [comment]
awesome! thanks!

I think this was the real source of the issue which now is fixed: TooTallNate/node-degenerator#6

@timaschew many thanks for all your help on this!

It'd be a good practice not to depend on branched dependencies.

Tags are harder to delete. It's a smart thing what you did here! I'll use this practice in the future (along with the npm-shrinkwrap think :wink: )

Thanks!

**Pull request closed without merging**
